### ISSUE TITLE
Implement `first` and `last` for ClosedInterval

### ISSUE THREAD

**Issue by iamed2** [JuliaMath/IntervalSets.jl#34]
Iteration doesn't make sense for ClosedInterval but first and last are known points.

**Comment by dlfivefifty** [comment]
We now have `leftendpoint(d)`, `rightendpoint(d)`, and `endpoints(d)`. Is there a good reason we need `first` and `last` as well? (I can't think of any generic code that would benefit from this override.)

**Comment by bgroenks96** [comment]
We were just discussing this here: rafaqz/ModelParameters.jl/issues/32

It might be helpful for generalizing between `Interval` and `Tuple` as bounds specifications.

However, there remains a question of what `first` and `last` should actually be for open intervals. Mathematically, they should be undefined. Pragmatically, they could be +/- `eps()` or just always use `leftendpoint`/`rightendpoint` and thus ignore whether the endpoints are open/closed.

**Comment by cstjean** [comment]
> It might be helpful for generalizing between Interval and Tuple as bounds specifications.

I often use `Tuple` for bounds specification too, because it's a convenient datastructure, but abstraction-wise, it's not right, is it? Generalizing between the two doesn't sound like a great argument to me. That said, I looked up `?first` to bolster my argument, but:

>   first(coll)
>
>  Get the first element of an iterable collection. **Return the start point of
>  an AbstractRange even if it is empty.**

Seems like Base also compromises on its semantics in the name of convenience...

**Comment by dlfivefifty** [comment]
I actually like the idea of supporting ` first ` and ` last ` (despite what I said 3 years ago)… I don’t really remember why we removed them, I think it was some code was being confused into thinking they are iterable

**Comment by timholy** [comment]
Intervals aren't iterable, which to me is the best argument to avoid `first`. We have `minimum` and `maximum`, can't one use those? They work for ranges too and are iteration-order independent, thus consistent with use in a non-iterable container.

**Comment by dlfivefifty** [comment]
Though it's not a complete replacement:
```julia
julia> first(1:0)
1

julia> minimum(1:0)
ERROR: ArgumentError: range must be non-empty
Stacktrace:
 [1] minimum(r::UnitRange{Int64})
   @ Base ./range.jl:617
 [2] top-level scope
   @ REPL[12]:1
```

**Comment by timholy** [comment]
That behavior of `first` can exist only because of a special exemption for ranges; for every other empty container it (should be) an error, since there is no "first element of the iterable container" to obtain. Do you really think it would be better? Why should `first` return `minimum` for an interval? Why not `maximum`?

**Comment by timholy** [comment]
I'd say that the containment criterion depends on there being an order, but that's distinct from an iterability order. After all, would you say that `first(5:-1:3)` is 3? But `3 < 5` so it must be first.

**Comment by hyrodium** [comment]
Is this issue still active? It seems there's no solid reason to introduce the `first` and `last` methods.
